@startuml TodoApp

skinparam classAttributeIconSize 0

namespace TodoApp.Domain.Interfaces {
    interface "IRepositorio<T>" {
        +Incluir(T entidade)
        +Alterar(T entidade)
        +Excluir(T entidade)
        +Excluir(Guid id)
        +ObterTodos(Guid idUsuario)
        +ObterPorId(Guid id)
    }

    interface INotificador {
        +Notificacoes: List<Notificacao>
        +PossuiInconsistencias: bool
        +Adicionar(Notificacao)
    }

    interface IUsuarioRepositorio {
        +Task<bool> Autenticar(Usuario)
    }

    interface ITodoRepositorio {}
}

@enduml